{% set name = "azure-mgmt-authorization" %}
{% set version = "4.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.zip
  sha256: 69b85abc09ae64fc72975bd43431170d8c7eb5d166754b98aac5f3845de57dc4

build:
  number: 0
  noarch: python
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - isodate <1.0.0,>=0.6.1
    - python >=3.7
    - msrest >=0.7.1
    - azure-common >=1.1,<2.dev0
    - azure-mgmt-core >=1.3.2,<2.0.0

test:
  imports:
    - azure.mgmt.authorization
    - azure.mgmt.authorization.v2015_06_01
    - azure.mgmt.authorization.v2015_06_01.models
    - azure.mgmt.authorization.v2015_06_01.operations
    - azure.mgmt.authorization.v2015_07_01
    - azure.mgmt.authorization.v2015_07_01.models
    - azure.mgmt.authorization.v2015_07_01.operations
    - azure.mgmt.authorization.v2018_01_01_preview
    - azure.mgmt.authorization.v2018_01_01_preview.models
    - azure.mgmt.authorization.v2018_01_01_preview.operations
    - azure.mgmt.authorization.v2018_07_01_preview
    - azure.mgmt.authorization.v2018_07_01_preview.models
    - azure.mgmt.authorization.v2018_07_01_preview.operations
    - azure.mgmt.authorization.v2018_09_01_preview
    - azure.mgmt.authorization.v2018_09_01_preview.models
    - azure.mgmt.authorization.v2018_09_01_preview.operations

about:
  home: https://github.com/Azure/azure-sdk-for-python
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Microsoft Azure Authorization Management Client Library for Python
  doc_url: https://docs.microsoft.com/python/api/overview/azure/authorization
  dev_url: https://github.com/Azure/azure-sdk-for-python

extra:
  recipe-maintainers:
    - dhirschfeld
    - andreyz4k
