{% set name = "azure-mgmt-authorization" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.zip
  sha256: 9a9fc16866b46387853381ab4fa0f84c1765e0afea5b0124709ea9fae10ee752

build:
  number: 0
  noarch: python
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - pip
    - python
  run:
    - azure-common >=1.1,<2
    - msrest >=0.5.0
    - msrestazure >=0.4.32,<2.0.0
    - python

test:
  imports:
    - azure.mgmt.authorization
    - azure.mgmt.authorization.v2015_06_01
    - azure.mgmt.authorization.v2015_06_01.models
    - azure.mgmt.authorization.v2015_06_01.operations
    - azure.mgmt.authorization.v2015_07_01
    - azure.mgmt.authorization.v2015_07_01.models
    - azure.mgmt.authorization.v2015_07_01.operations
    - azure.mgmt.authorization.v2018_01_01_preview
    - azure.mgmt.authorization.v2018_01_01_preview.models
    - azure.mgmt.authorization.v2018_01_01_preview.operations
    - azure.mgmt.authorization.v2018_07_01_preview
    - azure.mgmt.authorization.v2018_07_01_preview.models
    - azure.mgmt.authorization.v2018_07_01_preview.operations
    - azure.mgmt.authorization.v2018_09_01_preview
    - azure.mgmt.authorization.v2018_09_01_preview.models
    - azure.mgmt.authorization.v2018_09_01_preview.operations

about:
  home: https://github.com/Azure/azure-sdk-for-python
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Microsoft Azure Authorization Management Client Library for Python
  doc_url: https://docs.microsoft.com/python/api/overview/azure/authorization
  dev_url: https://github.com/Azure/azure-sdk-for-python

extra:
  recipe-maintainers:
    - andreyz4k
